version: 2
jobs:
    build:
        docker:
            - image: perl:latest
        steps:
            - restore-cache:
                keys:
                    - cpanm-{{ checksum ".circleci/cpanm.sh" }}
                    - cpanm-
            - checkout
            - run: sh ./.circleci/cpanm.sh
            - run: carton install
            - save-cache:
                key: cpanm-{{ checksum ".circleci/cpanm.sh" }}
                    paths: /usr/local/lib/perl5
                    
            
