version: 2
jobs:
    build:
        docker:
            - image: perl:latest
        steps:
            - checkout
            - run: cpanm Carton Module::Install Module::Install::AuthorTests Module::Install::Repository Module::Install::TestBase
            - run: carton install
            
