version: 2
jobs:
    build:
        docker:
            - image: perl:latest
        steps:
            - checkout
            - restore-cache:
                keys:
                    - cpanm-{{ checksum ".circleci/cpanm.sh" }}
            - run: sh .circleci/cpanm.sh
            - run: carton install
            - save-cache:
                key: cpanm-{{ checksum ".circleci/cpanm.sh" }}
                paths:
                    - /usr/local/lib/perl5
                    - /usr/local/bin
            - run: carton exec -- nim
